### PR TITLE
chore: Upgrade AWS SDK dependencies

### LINKED ISSUE #90: Failure to read S3 data from LocalStack
I have a working setup with the following:
* LocalStack Docker container with S3 (image ID 9c511c26795f)
* Containerized NEAR Lake Indexer that dumps data into the LocalStack instance

Unfortunately, when I tried to consume data from the instance using near-lake-framework-rs I encountered the following rather cryptic error:
```
Failed to get block heights from bucket near-lake-custom: AWS S3 error. Retrying in 1s...
```

After tinkering with this library and printing some extra fields inside `LakeError` I finally got the actual underlying error:
```
ServiceError(ServiceError { source: ListObjectsV2Error { kind: Unhandled(Unhandled { source: XmlDecodeError { kind: Custom("encountered invalid XML root: expected ListBucketResult but got StartEl { name: Name { prefix: \"\", local: \"ListAllMyBucketsResult\" }, attributes: [], closed: false, depth: 0 }. This is likely a bug in the SDK.")
            }
        }), meta: Error { code: None, message: None, request_id: None, extras: {}
        }
    }, raw: Response { inner: Response { status: 200, version: HTTP/1.1, headers: {
                "content-type": "application/xml",
                "access-control-allow-origin": "*",
                "access-control-allow-methods": "HEAD,GET,PUT,POST,DELETE,OPTIONS,PATCH",
                "access-control-allow-headers": "authorization,cache-control,content-length,content-md5,content-type,etag,location,x-amz-acl,x-amz-content-sha256,x-amz-date,x-amz-request-id,x-amz-security-token,x-amz-tagging,x-amz-target,x-amz-user-agent,x-amz-version-id,x-amzn-requestid,x-localstack-target,amz-sdk-invocation-id,amz-sdk-request",
                "access-control-expose-headers": "etag,x-amz-version-id",
                "vary": "Origin",
                "content-length": "332",
                "x-amz-request-id": "8c3f3858-f21d-42da-86b9-56713bac2f68",
                "x-amz-id-2": "s9lzHYrFp76ZVxRcpX9+5cjAnEH2ROuNkd2BHfIa6UkFVdtjf5mKR3/eTPFvsiP/XV/VLi31234=",
                "connection": "close",
                "date": "Mon, 20 Nov 2023 12:11:26 GMT",
                "server": "hypercorn-h11"
            }, body: SdkBody { inner: Once(Some(b"<?xml version='1.0' encoding='utf-8'?>\n<ListAllMyBucketsResult><Owner><DisplayName>webfile</DisplayName><ID>75aa57f09aa0c8caeab4f8c24e99d10f8e7faeebf76c078efc7c6caea54ba06a</ID></Owner><Buckets><Bucket><Name>near-lake-custom</Name><CreationDate>2023-11-20T12:11:21.661475Z</CreationDate></Bucket></Buckets></ListAllMyBucketsResult>\n")), retryable: true
            }
        }, properties: SharedPropertyBag(Mutex { data: PropertyBag, poisoned: false, ..
        })
    }
})
```

The error says that "This is likely a bug in the SDK", so it makes me think we should just try upgrading the S3 SDK this library is using (latest is 0.38, you are using 0.23)

### PR DESCRIPTION
**Pull request by khorolets**
This PR introduced **beta.3** for 0.8.0 version

- [x] Upgrade AWS SDK dependencies to the latest (resolves #90)
- [x] Improve AWS SDK error propagation to simplify debugging

### CODE REVIEW

**Comment by itegulov** [comment]
I can confirm that this branch works on my machine!

**Comment by itegulov** [comment]
Could you also update the relevant section in README? I believe the way you need to set up credentials is slightly different now

**Comment by khorolets** [comment]
> Could you also update the relevant section in README? I believe the way you need to set up credentials is slightly different now

I've updated it a bit. Although nothing has changed in the way, I've just adjusted the README example to be more straightforward.

**Review by telezhnaya — APPROVED** [review]
LGTM

**Pull request merged**
